config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'messages/index'
  resources :users, only: [:edit, :update]
  resources :rooms, only: [:new, :create, :destroy] do
    resources :messages, only: [:create, :index]
  end
  root to: "rooms#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  # MessageテーブルとActive Storageテーブルの画像ファイルを紐づけた
  # has_one_attached :ファイル名 と書けば、"モデル名.ファイル名"でファイルにアクセスできる。
  # 例) Messageモデルのimageファイル : Message.imageと書けば、その画像の持つパラメータのキーにもできる。
  has_one_attached :image

  # ▼は、validationに条件分岐をつけている。
  # 私の理解 : 以下2つの項目を満たすとき、validation(検証)するという意味
  ## ❶ :content, presence: true -> "content"が空かどうか。
  ## ❷ unless: :was_attatched?  -> "画像"が添付されているかどうか。unlessだから、画像添付(戻り値がtrue)されていたらスルーされる?

  # <投稿できる場合>
  # ❶contentが空、❷画像が添付されている(戻り値がtrue)
  # ❶contentは空ではない、❷画像が添付されていない(戻り値がfalse)

  # <投稿できない場合> *❶❷どちらもtrue
  # ❶contentが空、❷画像が添付されていない(戻り値がfalse -> unlessがtrueになるということ)

  validates :content, presence: true, unless: :was_attached?

  def was_attached?
    self.image.attached?
  end

end

app/models/room.rb
class Room < ApplicationRecord
  # roomの削除(destroyアクション)を行うと、子のmessagesも一緒に削除する
  has_many :room_users, dependent: :destroy
  has_many :users, through: :room_users
  # roomの削除(destroyアクション)を行うと、子のmessagesも一緒に削除する
  has_many :messages, dependent: :destroy

  validates :name, presence: true

end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true

  has_many :room_users
  has_many :rooms, through: :room_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  # @messageで、チャットを保存していく。
    @message = Message.new
  # roomとmessageは親子関係なので、indexアクションに飛んできたとき、paramsにroom_idが格納されている。
    @room = Room.find(params[:room_id])
  # @room.messages : チャットルームに紐づいている全てのメッセージは、user_idと紐づいている。
  # includes(:user) : 一度の参照で、全ての紐付けを獲得することで、N+1問題を解消している。
    @messages = @room.messages.includes(:user)
  end

  def create
    # Roomレコードから、現在の部屋情報を引き出す
    @room = Room.find(params[:room_id])
    # その部屋情報に紐づく、チャット情報(ユーザーid含む)を新たに保存する。
    @message = @room.messages.new(message_params)
    if  @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
  end

  def new
    @room = Room.new()
  end

  def create
    # フォームから送られてくるparamsには、❶チャットルーム名:name, ❷参加ユーザー名:user_ids[]が含まれている。
    @room = Room.new(room_params)
    if @room.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end
  
  private

  def room_params
    # ストロングパラメータ -許可記述のやり方-
    #   単数のパラメータを許可 -> :name属性
    #   複数のパラメータを許可 -> name属性: []
    params.require(:room).permit(:name, user_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to "/"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css"> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<div class="chat-header">
  <div class="room-name">
    <%= @room.name %>
  </div>
  <div class="chat-exit">
    <%= link_to 'チャットを終了する', room_path(@room), method: :delete %>
  </div>
</div>

<div class="messages">
  <%# 全てのチャットメッセージ@messagesひとつひとつの要素messageに対して、renderを実行する。 %>
  <%= render partial: 'message', collection: @messages %>
</div>

<%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
  <div class="form-box">
    <%= f.text_field :content, class: 'message-form', placeholder: 'type a message' %>
    <%# 画像ボタンの実装 %>
    <%# label要素によって、小クラス(画像ボタン部分)も一緒にクリックしたとみなしてくれる %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'message-send' %>
<% end %>

app/views/messages/_message.html.erb
<div class="message-box">
  <div class="message-header">
    <div class="message-user">
    <%# ユーザー名を表示する %>
      <%= message.user.name %>
    </div>

    <div class="message-date">
    <%# 投稿時刻を表示させる %>
      <%= l message.created_at%>
    </div>
  </div>
  <div class="message-content">
    <%# チャットを表示する %>
    <%= message.content %>
  </div>
  <%# image_tag : モデル.ファイル名でモデルから画像を簡単に呼び出せるヘルパーメソッド。 %>
  <%# message.image.attached? で添付されているかチェックする %>
  <%# variant(変形)メソッド : 画像の大きさを調整する %>
  <%= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %>
</div>

app/views/messages/_side_bar.html.erb
    <div class="chat-create">
        <div class="user-box">
            <%= link_to current_user.name, edit_user_path(current_user) %>
        </div>
        <div class="create-box">
            <%= link_to 'Create chatroom', new_room_path %>
        </div>
    </div>
    
    <div class="room-info">
        <% current_user.rooms.each do |room| %>
            <div class="room">
                <div class="room-name">
                    <%= link_to room.name, room_messages_path(room) %>
                </div>
            </div>
        <% end %>
    </div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>

  <div class="chat">
    <%= render "main_chat" %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "/messages/side_bar" %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :name, :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <%# 【チャットルームの新規作成機能 - チャットするユーザーをプルダウンで選択 - 】 %>
        <%# select : optionで記載された情報を含んだプルダウンを生成する.  %>
        <%# プルダウンが押されると、❶selectのname属性と❷optionのvalue属性が、params{key(name属性): value(value属性)に格納されて、コントローラーに送られる %>
        <%# room[user_ids][]という記述の意味 %>
        <%#   1つの部屋には複数(自身+選択したユーザ)のuserが存在するので、複数の箱を用意する必要がある。
        <%#   そこで、room[user_ids][]と定義し、まず▼で前半の"[user_ids]"に選択したユーザー情報を格納する %>
        <select name="room[user_ids][]">
          <option value="">チャットするユーザーを選択してください</option>
          <%# モデル名.where("条件") : 条件に一致したレコードと配列を取得できる %>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%= user.id %>><%= user.name %></option>
          <% end %>
        </select>
        <%# type="hidden" : 画面上に表示されないinput要素を作成する %>
        <%#   次に、後半の"[]"にログイン中の自身の情報を格納し、params{ room: {user_ids: ["user_ids", "current_user.id"]}として、送信する %>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model:current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>